### ISSUE TITLE
Request: adding a property if the file is currently checked

### ISSUE THREAD

**Issue by csdvrx** [itchyny/vim-gitbranch#10]
Hello,

I was trying to write my own light plugin, but yours seem to be exactly what I had in mind!

Would it be possible to just add the status of the file as #info property?

I would suggest to keep it simple (ex: find if the file is excluded using .gitignore, find if the file modified or staged using .git/index) to keep your excellent plugin very light.

Thanks!

**Comment by itchyny** [comment]
I don't think this plugin is the appropriate place to provide such feature. This plugin focuses on the single feature for integration with various plugins. You can create and publish your own plugin. Note that ambiguous name like `info` leads to uncontrollable requests of customization flags.
