### ISSUE TITLE
Add example how to use gitbranach with airline

### ISSUE THREAD

**Issue by astier** [itchyny/vim-gitbranch#5]
Maybe it would be good for the uninformed users to add an example to the readme how to use gitbranch with airline. Here is how I do it:

```
let g:airline_section_b = '%{gitbranch#name()}'
```

This is good if one doesn't want to use a heavy plugin like fugitive just to show the current branch in the airline.

**Comment by itchyny** [comment]
That configuration looks like trivial for vim-airline users. Honestly speaking, I don't want to include configuration for vim-airline in my repository, sorry.

**Comment by astier** [comment]
No problem. Just for reference `let g:airline#extensions#branch#custom_head = 'gitbranch#name'` might be a better approach than my above solution because it doesn't override the b_section completely which would also remove the hunk-indicator.
