### ISSUE TITLE
Branch of parent instead of submodule is displayed when editing `COMMIT_EDITMSG`

### ISSUE THREAD

**Issue by spenserblack** [itchyny/vim-gitbranch#8]
It looks like something similar has been brought up before (#2), but this is slightly different. When *writing a commit message* in a submodule, the parent's branch is displayed. This seems to be due to `COMMIT_EDITMSG` of a submodule existing in `../.git/modules/<submodule name>`. It can be confusing to write a commit message when in a submodule and see the parent's branch.

According to `:PlugSnapshot`, I'm on commit 8118dc1cdd387bd609852be4bf350360ce881193

**Comment by itchyny** [comment]
Thanks for reporting, fixed.
